Repository SAP/crossplane-provider-btp, pull requests merged in 2025-09, with the labels that each got.

#348 fix (#341): external name validation for subscription
  internal/clients/subscription/subscription.go
  internal/clients/subscription/subscription_test.go
Labels: release-notes/bugfix

#353 test: verify external-name in ServiceManager Tf client
  internal/clients/servicemanager/service_manager_tf_client_test.go
Labels: release-notes/ignore

#354 test: verify external-name in CloudManagement Tf client
  internal/clients/cis/cis_tf_client_test.go
Labels: release-notes/ignore

#356 test: test usage of external-name for cf environment lookup
  internal/clients/cfenvironment/cfenvironment.go
  internal/clients/cfenvironment/cfenvironment_test.go
  internal/clients/fakes/provisioningserviceclient_fake.go
  internal/clients/kymaenvironment/kymaenvironment_test.go
Labels: release-notes/ignore

#351 feat(Subaccount): change external-name to the id
  internal/controller/account/subaccount/fakes.go
  internal/controller/account/subaccount/subaccount.go
  internal/controller/account/subaccount/subaccount_test.go
Labels: release-notes/others
